### ISSUE TITLE
Correct string attributes in components to be in the real Python type for the Reduced scene generation

### ISSUE THREAD

**Issue by olivier-goury** [SofaDefrost/ModelOrderReduction#1]
Change generated scenes in Python to have parameters that are real python types and not always string: e.g. performECSW=True instead of performECSW="True", nbModes=15 instead of nbModes="15", etc...

**Comment by damienmarchal** [comment]
Yes!

**Comment by VannesteFelix** [comment]
Fixed with commit 6c3b27319b16a98ea1f66309ad213e09b9fe4af7
