### ISSUE TITLE
Error name 'go' is not defined after phase 2 in the modelOrderReduction.ipynb under \tools folder

### ISSUE THREAD

**Issue by zhichaoliu0921** [SofaDefrost/ModelOrderReduction#12]
`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-5979d552fe76> in <module>()
      5 content = [x.strip() for x in content]
      6 
----> 7 data = [go.Bar(x=range(1, len(content)+1),
      8             y=content)]
      9 

NameError: name 'go' is not defined`

**Comment by VannesteFelix** [comment]
notebook have been updated and fixed
