### ISSUE TITLE
[forcefield] addSubKToMatrix

### ISSUE THREAD

**Issue by EulalieCoevoet** [SofaDefrost/ModelOrderReduction#31]
The method `addSubKToMatrix` has been removed in SOFA [PR#2244](https://github.com/sofa-framework/sofa/pull/2244), and you're still using it in `HyperReducedRestShapeSpringsForceField`.

**Comment by olivier-goury** [comment]
Thanks for pointing this out Eulalie, that is right!
I think @alxbilger  is preparing a PR?

**Comment by alxbilger** [comment]
> I think @alxbilger is preparing a PR?

Yes, I just forgot to push it. It's done now.
