### ISSUE TITLE
Unable to compile Sofa with MOR

### ISSUE THREAD

**Issue by samFabrice** [SofaDefrost/ModelOrderReduction#45]
Hi @VannesteFelix ,
I can no longer compile SOFA with MOR.
I'm using the latest version of Sofa the 22.06 , I'm on the master branch of MOR and i'm on ubuntu 20.04 
I wonder if it's not from the update I had to do. Because it worked really well before and we had validated it.

**Comment by VannesteFelix** [comment]
Thanks for the info @samFabrice, looking into right now.
