### ISSUE TITLE
Error when compiling sofa v22.06 with MOR v22.06

### ISSUE THREAD

**Issue by hunoutl** [SofaDefrost/ModelOrderReduction#59]
I got a error when i tried to compile sofa with MOR plugin (in-tree build).
I am on the same release on both with the v22.06 but i got a strange disabled header : 

> SOFA_DISABLED_HEADER("v21.12", "v22.06", "sofa/linearalgebra/CompressedRowSparseMatrix.h")
GCC error "This header has been DISABLED since " "v22.06" " " "after being deprecated on " "v21.12" ". " "To fix this error you must include " "sofa/linearalgebra/CompressedRowSparseMatrix.h" " instead. "

Compiling with ninja, i have same error type with other header.
This is not the behavior I expected. Maybe i done somethings wrong or didn't understood.
I can provide a longer log if needed

**Comment by alxbilger** [comment]
This is because files have been moved in SOFA, and includes in the plugin did not follow the move. The plugin has been fixed on the master branch (#56), but not on the v22.06 branch for some reasons. It is now patched and you can update your v22.06 branch.

Thank you for pointing the problem.
