### ISSUE TITLE
Error building the MOR plugin : ‘checkOutOfBoundsIndices’ is not a member of RestShapeSpringsForceField

### ISSUE THREAD

**Issue by GaetanDesrues** [SofaDefrost/ModelOrderReduction#9]
Hi, I successfully build my sofa version (17.12.02) with STLIB plugin on fedora 28 in Qt 5.5. I tried to add the last version of the MOR plugin and I get this error :

In file **/HyperReducedRestShapeSpringsForceField.inl:186:72** :

**error: ‘checkOutOfBoundsIndices’ is not a member of ‘sofa::component::forcefield::RestShapeSpringsForceField**

Here is the compile output :

`[ 99%] Building CXX object external_directories/externals-plugins/ModelOrderReduction/CMakeFiles/ModelOrderReduction.dir/src/component/forcefield/HyperReducedRestShapeSpringsForceField.cpp.o
In file included from /sofa/src/externals-plugins/ModelOrderReduction/src/component/forcefield/HyperReducedRestShapeSpringsForceField.cpp:19:0:
/sofa/src/externals-plugins/ModelOrderReduction/src/component/forcefield/HyperReducedRestShapeSpringsForceField.inl: In instantiation of ‘bool sofa::component::forcefield::HyperReducedRestShapeSpringsForceField<DataTypes>::checkOutOfBoundsIndices() [with DataTypes = sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double>]’:
/sofa/src/externals-plugins/ModelOrderReduction/src/component/forcefield/HyperReducedRestShapeSpringsForceField.cpp:43:45:   required from here
/sofa/src/externals-plugins/ModelOrderReduction/src/component/forcefield/HyperReducedRestShapeSpringsForceField.inl:186:72: error: ‘checkOutOfBoundsIndices’ is not a member of ‘sofa::component::forcefield::RestShapeSpringsForceField<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> >’
     if (!RestShapeSpringsForceField<DataTypes>::checkOutOfBoundsIndices(m_indices, this->mstate->getSize()))
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/sofa/src/externals-plugins/ModelOrderReduction/src/component/forcefield/HyperReducedRestShapeSpringsForceField.inl:191:72: error: ‘checkOutOfBoundsIndices’ is not a member of ‘sofa::component::forcefield::RestShapeSpringsForceField<sofa::defaulttype::StdVectorTypes<sofa::defaulttype::Vec<3, double>, sofa::defaulttype::Vec<3, double>, double> >’
     if (!RestShapeSpringsForceField<DataTypes>::checkOutOfBoundsIndices(m_ext_indices, getExtPosition()->getValue().size()))
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [external_directories/externals-plugins/ModelOrderReduction/CMakeFiles/ModelOrderReduction.dir/build.make:89: external_directories/externals-plugins/ModelOrderReduction/CMakeFiles/ModelOrderReduction.dir/src/component/forcefield/HyperReducedRestShapeSpringsForceField.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:11819: external_directories/externals-plugins/ModelOrderReduction/CMakeFiles/ModelOrderReduction.dir/all] Error 2
gmake: *** [Makefile:163: all] Error 2
18:44:04: The process "/usr/bin/cmake" exited with code 2.`

How could I fix this issue to build sofa with the mor plugin ?

**Comment by VannesteFelix** [comment]
Hi @GaetanDesrues ,

thanks for the issue.

First just to let you know that we have only tested ModelOrderReduction on Ubuntu 18 & Windows 10 yet. So you are the first one to give us feedback for Fedora, thanks in advance for that and sorry if some unexpected errors occurs.

Concerning your current problem, it might come from the fact that sofa 17.12.02 is already a bit old and doesn't include modifications we have made/push into sofa in order for our plugin to work.

Is there a specific reason for you to use this version ?
If not try with the last one [v18.12.01](https://www.sofa-framework.org/download/) or directly with the [sources](https://github.com/sofa-framework/sofa)

**Comment by GaetanDesrues** [comment]
Hi @VannesteFelix, thank you for your reply.
Unfortunately I am using another plugin for the project only compatible with this previous version of sofa (v17.12). Is there any possibility to make the plugin compatible with this version of sofa ?

**Comment by VannesteFelix** [comment]
I don't think its possible for the current state of the plugin or maybe but with some tremendous effort.

You can maybe try yourself by checkout to a commit from early 2018 but you won't have all the currently implemented HyperReducedForceField and all the python utilities to help you reduce a model or you will have to copy past the current one and modify them (but not much).

Which plugin are you using ?
